FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
COPY accurolab/Data-ML/ml/production/app /app
COPY accurolab/Data-ML/ml/production/requirements.txt .
RUN pip --no-cache-dir install -r requirements.txt